### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by Alces-lab** [windingwind/zotero-pdf-translate#30]
Engine not available, invalid secret, or request too fast.
Please consider using another translate engine or posting issue here: https://github.com/windingwind/zotero-pdf-translate/issues
        TypeError: xhr.response.trans_result is undefined

**Comment by windingwind** [comment]
Are you using baidu? Your secret is invalid, as the error log said.

**Comment by Alces-lab** [comment]
I'm a beginner Github user and don't know how to get the secret, can you tell me where to look for it, or can you tell me the search engine secret?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年3月24日 20:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [windingwind/zotero-pdf-translate] Request Error (Issue #30)


Are you using baidu? Your secret is invalid, as the error log said.

―

**Comment by windingwind** [comment]
See #20

**Comment by Opheliaa1** [comment]
开发者你好，我使用默认的谷歌翻译也出现了Engine not available, invalid secret, or request too fast.请问怎么解决呢

**Comment by Opheliaa1** [comment]
重新下载安装后已解决，谢谢❤️

发自我的iPad

**Comment by XiangYeTan** [comment]
hello，Good evening！When I use the “Baidu Translate”，The zotero notices me this fault.  I use the  secret:My_ID#My serect.
I need your help，Thanks！ I wish you send me a email ，my email is tanxinagye@126.com. Thank you very much!
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Baidu*, not Zotero or the PDF Translate addon.
        52003:UNAUTHORIZED USER

**Comment by windingwind** [comment]
@XiangYeTan
The MY_ID and MY_SECRET is just a placeholder. You must sign up an account following the documentation and setup the service. Replace these placeholder with your key and secret. 
BTW, please discuss in a new issue.
