### ISSUE TITLE
[Bug]弹窗中不再出现“添加文本到笔记”和“添加翻译结果到笔记”按钮

### ISSUE THREAD

**Issue by aaronkhq** [windingwind/zotero-pdf-translate#533]
插件版本：v1.1.0-7
电脑：macos M1 Ventura 13.0.1 (22A400)
zotero：7.0.0-beta.32

paf-translate是我高频使用的zotero插件，非常实用，感谢创作者！！
在zotero更新新版本之后，目前发现，有三个bug：
1. 在选中文本后，弹窗中不再出现“添加文本到笔记”按钮；
2. 在选中文本后，弹窗中不再出现“添加翻译结果到笔记”按钮；
3. 右侧栏只包含翻译源文本，不显示翻译的结果。

如图：
<img width="1884" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/65768952/bafd6a2b-dca7-450b-988e-102a089ef1dd">

期待作者能排查一下，非常感谢！辛苦！！

**Comment by noneaddress** [comment]
插件版本：v1.0.24
电脑：Win10
zotero：6.0.26
存在同样问题。相关设置均已打开。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/74852100/c5fdf982-5aad-4e63-a697-e6ecfcf0eaca)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/74852100/ae32f0bd-1e87-4feb-9cf7-27672f2ba5b1)

**Comment by pengxy0** [comment]
这个bug还存在着。我的也是这样子。点击添加笔记仍旧不起作用，希望作者可以修复一下
![image](https://github.com/windingwind/zotero-pdf-translate/assets/130196652/c6cd685e-5d93-4667-98c0-d4a97680cace)

**Comment by noneaddress** [comment]
> 插件版本：v1.1.0-7 电脑：macos M1 Ventura 13.0.1 (22A400) zotero：7.0.0-beta.32
> 
> paf-translate是我高频使用的zotero插件，非常实用，感谢创作者！！ 在zotero更新新版本之后，目前发现，有三个bug：
> 
> 1. 在选中文本后，弹窗中不再出现“添加文本到笔记”按钮；
> 2. 在选中文本后，弹窗中不再出现“添加翻译结果到笔记”按钮；
> 3. 右侧栏只包含翻译源文本，不显示翻译的结果。
> 
> 如图： <img alt="image" width="1884" src="https://user-images.githubusercontent.com/65768952/259931368-bafd6a2b-dca7-450b-988e-102a089ef1dd.png">
> 
> 期待作者能排查一下，非常感谢！辛苦！！

@aaronkhq 第三个问题，您要不看看这里有没有设置呢？
![image](https://github.com/windingwind/zotero-pdf-translate/assets/74852100/43fbb847-231b-4980-b7f7-bdd27c5ddb03)

**Comment by zhimaerfan** [comment]
1.解决方案：不提示添加到笔记按钮，是因为你右侧没有打开笔记。
2.bug反馈：点击添加到笔记按钮无效，M2 MacBook Air OS13.4。
感谢开发者的伟大工作，这次修复了弹窗随着点击变化大小的bug。这非常棒！

1.Solution: It doesn't prompt the Add to Notes button because you don't have notes open on the right side.
2. bug feedback: clicking the add to notes button does not work, M2 MacBook Air OS13.4.
Thanks to the great work of the developers, this fixes the bug where the popup window changes size with a click. this is great!
