### ISSUE TITLE
Translation with Google engine does not match the original Google Translation

### ISSUE THREAD

**Issue by rolfdstoll** [windingwind/zotero-pdf-translate#56]
The translation quality of the extension is very poor and faulty when the Google engine is selected and does not match the much better translation that is obtained with the original Google Translate.

**Comment by windingwind** [comment]
I cannot control the quality of the results. The Google API I use is the one that the official Chrome Google Translate Extension uses.

If you are not satisfied with Google Translation, there is always a choice to use other services, like Microsoft Azure Translation and DeepL.

**Comment by rolfdstoll** [comment]
Google's translation would be good enough for me, but unfortunately there is a significant quality difference between the add-on's translation and the official Google Chrome translation engine, which I call via the browser .  I use the PDF Translate version 0.3.12 and I translate from American English to German.

**Comment by windingwind** [comment]
I understand your concern. I'll try to add an engine using the web API of Google.

**Comment by windingwind** [comment]
There are two ways to access a translation: website/desktop app or API. API allows you to get translations from the server directly.

Theoretically speaking, applications, including this add-on, is expected to use the API way. Translation service providers, like Google and DeepL, require an account and a secret to access the API to prevent malicious access.

We use some technical strategies to fake a website request, that's why some translation engines of this add-on do not require secret. However, this may be unstable, for companies can easily know if you are a real human or not.

Why you can use DeepL free via browser, while we need a secret in this add-on? Monitoring DeepL website requests is very unstable. 

What's a secret? Take DeepL as an example, see https://www.deepl.com/docs-api. It is not your account secret. It only controls your API.

**Comment by windingwind** [comment]
Hi,
I'll close this issue. Feel free to open it again~
