### ISSUE TITLE
[Feature] 添加笔记可否把发音也添加进去

### ISSUE THREAD

**Issue by Z0o0o** [windingwind/zotero-pdf-translate#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version: 

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

![image](https://github.com/windingwind/zotero-pdf-translate/assets/121789386/5f9b244a-4960-457e-a224-87a57de5c0ea)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/121789386/db3a524b-91b3-47b6-aae1-f1159cc00e91)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/121789386/d5b32b5e-7874-4b28-98d6-c7222458ca72)

**Comment by Z0o0o** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> * OS:
> * Zotero Version:
> * Plugin Version:
> 
> ### Describe the feature request
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Why do you need this feature?** A clear and concise description of why you need this feature.
> 
> ### Describe the solution you'd like
> ![image](https://user-images.githubusercontent.com/121789386/273438579-5f9b244a-4960-457e-a224-87a57de5c0ea.png) ![image](https://user-images.githubusercontent.com/121789386/273438619-db3a524b-91b3-47b6-aae1-f1159cc00e91.png) ![image](https://user-images.githubusercontent.com/121789386/273438631-d5b32b5e-7874-4b28-98d6-c7222458ca72.png)
> 
> ### Anything else?
> _No response_

**Comment by Lslightly** [comment]
The extension in previous version embedded the pronunciation in the translation result. But in version 1.0.25(or earlier versions), the pronunciation are placed into a button to pronounce the word.

It is annoying because I can't copy the pronunciation to annotations and recall the pronunciation simply through annotations. I have to select the new word again. The cost of re-selection is much more expensive than a simple click. When I collect these separated annotations to review these new words, again I have to open other translation tools to find the pronunciation for these new words.

So, it does matter to add pronunciation in the translation result for the convenience of copying/pasting. An option to customize whether to show the pronunciation is preferred for different users' tastes.
