### ISSUE TITLE
[Bug]对于特定语言自动翻译的关闭问题

### ISSUE THREAD

**Issue by Liwt0** [windingwind/zotero-pdf-translate#65]
**Describe the bug**
对于语言为中文,zh,zh-CN的文章 ，设定关闭自动翻译后，高亮文本时仍会自动保存批注。对于短句会自动复制，对于长句会变为一堆逗号

**To Reproduce**
1. 高级中关闭自动翻译的语言设为zh，zh-CN
2. 在中文文献选中文本高亮
3. 会出现自动保存批注
5. 短句会复制，长句变为一堆逗号

**Expected behavior**
希望可以在中文文献中成功关闭自动翻译

**Screenshots**
![image](https://user-images.githubusercontent.com/90240641/161363423-e526a0b3-9918-4e01-8738-51660c8fa7f8.png)

![image](https://user-images.githubusercontent.com/90240641/161363307-b3518813-54c0-4337-bdc2-11bebdb95341.png)

![image](https://user-images.githubusercontent.com/90240641/161363368-dfce0f3f-f91c-493b-95e4-9f3350af1f30.png)

![image](https://user-images.githubusercontent.com/90240641/161363375-7121377c-52a0-45e4-8f75-ea9078afe966.png)

![image](https://user-images.githubusercontent.com/90240641/161363382-f1f604fb-a743-424e-be63-6c834ece5dc0.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.4
 - Addon Version：0.3.17

**Comment by windingwind** [comment]
I guess there are 3 different issues.

1. Disable translation for certain languages. Reopen the PDFs after you changed this setting, otherwise this may not work.
2. Disable annotation translation for certain languages. There are some bugs with this feature.
3. Translation issue. Translation from zh to zh is undefined and the strange result may also be a PDF encode error, for which I can make no promise.

Please post a screenshot of the PDF information with the language field, like this:
![image](https://user-images.githubusercontent.com/33902321/161365575-4a188dea-3713-4e2f-8481-b588b49abd28.png)

**Comment by Liwt0** [comment]
![image](https://user-images.githubusercontent.com/90240641/161365862-3ffff460-81c2-47cb-847c-9084311f16bb.png)


1.中文被翻译的问题：重新打开PDF后得到解决
2.自动翻译批注的问题：选择高亮后，对于中文仍会被批注，而且内容为一些逗号
![image](https://user-images.githubusercontent.com/90240641/161365943-fe6e83c7-30dc-4864-bc13-eed9f4b38567.png)
![image](https://user-images.githubusercontent.com/90240641/161365953-2777c7f9-8cb5-426b-88ed-2a8522e6fd97.png)

**Comment by windingwind** [comment]
Fixed the automatic annotation translate bug in v0.3.18

**Comment by AoneWildernessWolf** [comment]
如果用了茉莉花插件，语言栏是“中文;"，在高级设置需要输入“中文;"，输入”中文“无效。不知道这个算不算bug

**Comment by windingwind** [comment]
> 如果用了茉莉花插件，语言栏是“中文;"，在高级设置需要输入“中文;"，输入”中文“无效。不知道这个算不算bug

不是bug。插件只会根据设置给出的语言进行判断

**Comment by Liwt0** [comment]
新版本插件已解决所有问题，感谢！
