### ISSUE TITLE
[Feature] Clarify IP block message

### ISSUE THREAD

**Issue by dstillman** [windingwind/zotero-pdf-translate#76]
We're getting numerous posts in the Zotero Forums from people running this plugin who seem to think that Zotero has blocked their IP address. I'm not sure what the current message is or when it appears, but could the message be updated to clarify that this is 1) from the PDF Translate plugin and 2) from whatever upstream service is actually doing the blocking, not from Zotero?

https://forums.zotero.org/discussion/95990/be-blacklisted-then-cant-use-translation-function
https://forums.zotero.org/discussion/96105/my-ip-address-was-blocked-how-to-deal-with-it
https://forums.zotero.org/discussion/96191/why-is-my-ip-blocked

**Comment by windingwind** [comment]
Thanks for letting me know. Actually, I had a lot of discussions about this IP block message: #64, #57, etc.

The message is generated from a template and the error message from the service provider.
`[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues`

I think it's clear enough. The cause & solution is also listed in common issue #6. I'm also bothered by tons of impolite questions about IP block.

I'll add `This message is from the translation service you are using, not Zotero.` Is that OK?

**Comment by dstillman** [comment]
`not Zotero or the PDF Translate plugin`? I assume you want to clarify that it's not from you either. But our main concern is just making sure people understand that they're using a plugin here, since we can't help them.

**Comment by windingwind** [comment]
Thanks. Will update this in the next release!
